
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb://localhost:27017/Project
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: Kartik_Project
        MONGO_INITDB_ROOT_USERNAME: admin 
        MONGO_INITDB_ROOT_PASSWORD: Kartik02@   
    networks:
      - backend


  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
